trainer: ocp

dataset:
  train:
    format: lmdb
    src: /data/shared/MLFF/SPICE/maceoff_split/train/
    key_mapping:
      reference_energy: energy
      force: forces
    transforms:
      normalizer:
        energy:
          mean: -140.80356519035792
          stdev: 69.1667169308504
        forces:
          mean: 0
          stdev: 1.0757999822144813
  val:
    src: /data/shared/MLFF/SPICE/maceoff_split/test/

logger: wandb

outputs:
  energy:
    shape: 1
    level: system
  forces:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: mae
      coefficient: 4
  - forces:
      fn: l2mae
      coefficient: 100

evaluation_metrics:
  metrics:
    energy:
      - mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae
