includes:
  - configs/s2ef/MD22/datasets/base.yml

dataset:
  train:
    format: lmdb
    src: /data/shared/MLFF/MD22/95_lmdb/Ac-Ala3-NHMe/train/
    key_mapping:
      y: energy
      force: forces
    transforms:
      normalizer:
        energy:
          mean: -26913.953
          stdev: 0.35547638
        forces:
          mean: 0
          stdev: 1.1291506
  val:
    src: /data/shared/MLFF/MD22/95_lmdb/Ac-Ala3-NHMe/val/
