includes:
  - configs/s2ef/MD22/datasets/base.yml

dataset:
  train:
    format: lmdb
    src: /data/shared/MLFF/MD22/95_lmdb/stachyose/train/
    key_mapping:
      y: energy
      force: forces
    transforms:
      normalizer:
        energy:
          mean: -68463.59
          stdev: 0.5940788
        forces:
          mean: 0
          stdev: 1.1104717
  val:
    src: /data/shared/MLFF/MD22/95_lmdb/stachyose/val/
