includes:
  - configs/s2ef/MD22/datasets/base.yml

dataset:
  train:
    format: lmdb
    src: /data/shared/MLFF/MD22/95_lmdb/buckyball-catcher/train/
    key_mapping:
      y: energy
      force: forces
    transforms:
      normalizer:
        energy:
          mean: -124776.7
          stdev: 0.64662045
        forces:
          mean: 0
          stdev: 1.0899031
  val:
    src: /data/shared/MLFF/MD22/95_lmdb/buckyball-catcher/val/
