model_dir: MODELPATH
dataset_src: None
identifier: 100ps
sim_type: ocp
seed: 123
save_freq: 100
steps: 200000
max_test_points: 10000

kcal: False
T_init: 500.
integrator: Langevin
integrator_config: {"timestep": 0.5, "temperature_K": 500., "friction": 0.5}
