includes:
  - configs/s2ef/MD22/datasets/base.yml

dataset:
  train:
    format: lmdb
    src: /data/shared/MLFF/MD22/95_lmdb/double-walled_nanotube/train/
    key_mapping:
      y: energy
      force: forces
    transforms:
      normalizer:
        energy:
          mean: -338224.16
          stdev: 3.3810701
        forces:
          mean: 0
          stdev: 1.0137014
  val:
    src: /data/shared/MLFF/MD22/95_lmdb/double-walled_nanotube/val/
