includes:
  - configs/s2ef/MD22/datasets/base.yml

dataset:
  train:
    format: lmdb
    src: /data/shared/MLFF/MD22/95_lmdb/AT-AT-CG-CG/train/
    key_mapping:
      y: energy
      force: forces
    transforms:
      normalizer:
        energy:
          mean: -101034.23
          stdev: 0.680055
        forces:
          mean: 0
          stdev: 1.2021886
  val:
    src: /data/shared/MLFF/MD22/95_lmdb/AT-AT-CG-CG/val/
