trainer: equiformerv2_forces

dataset:
  train:
    # format: fairchem.core.datasets.oc22_lmdb_dataset.OC22LmdbDataset
    format: lmdb
    src: data/oc22/s2ef/train/
    key_mapping:
      y: energy
      force: forces
    transforms:
      normalizer:
        energy:
          mean: 0.0
          stdev: 24.901469505465872
        forces:
          mean: 0.0
          stdev: 0.5111534595489502
      element_references:
        energy:
          file: configs/oc22/linref/oc22_linfit_coeffs.npz
    train_on_oc20_total_energies: True
    oc20_ref: configs/s2ef/all/coeff_2M.npz

  val:
    src: data/oc22/s2ef/val_id/

logger: wandb

outputs:
  energy:
    shape: 1
    level: system
  forces:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: mae
      coefficient: 2
  - forces:
      fn: l2mae
      coefficient: 100

evaluation_metrics:
  metrics:
    energy:
      - mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae
